/*
 * BombSweeperTypes.hpp
 *
 *  Created on: 10 août 2021
 *      Author: Kierann
 */

#ifndef SRC_SOFTWARE_06_BOMBSWEEPER_BOMBSWEEPERTYPES_HPP_
#define SRC_SOFTWARE_06_BOMBSWEEPER_BOMBSWEEPERTYPES_HPP_

enum BoxContent {
	GREEN_RUPEE = 0,
	BLUE_RUPEE = 1,
	RED_RUPEE = 2,
	SILVER_RUPEE = 3,
	GOLDEN_RUPEE = 4,
	RUPOOR = 5,
	BOMB = 6,
	HIDDEN = 7
};

#endif /* SRC_SOFTWARE_06_BOMBSWEEPER_BOMBSWEEPERTYPES_HPP_ */
